/*

Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/

'use strict';

function main() {
	for (let i = 286; true; i++) {
		let t = getTriangular(i);

		if (isPentagonal(t) && isHexagonal(t)) return t;
	}
}


function getTriangular(n) {
	return n * (n + 1) / 2;
}


function isPentagonal(n) {
	return ((Math.sqrt(24 * n + 1) + 1) / 6) % 1 === 0;
}


function isHexagonal(n) {
	return ((Math.sqrt(8 * n + 1) + 1) / 4) % 1 === 0;
}

console.time('main');

console.log(main());

console.timeEnd('main');